version: '3.8'

services:
  # FrontFuse Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3001}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL:-./database.sqlite}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5173}
    volumes:
      - backend_data:/app/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/health']
      interval: 30s
      timeout: 10s
      retries: 3

  # FrontFuse Frontend Hub
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - VITE_API_URL=${FRONTEND_URL:-http://localhost:3001}
      - NODE_ENV=${NODE_ENV:-production}
    depends_on:
      - backend
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3

  # Task Manager Micro-frontend
  task-manager:
    build:
      context: ./task-manager-app
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    environment:
      - FRONTFUSE_HUB_URL=${FRONTEND_URL:-http://backend:3001}
      - NODE_ENV=${NODE_ENV:-production}
    depends_on:
      - backend
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3002']
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - task-manager
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend_data:
    driver: local

networks:
  default:
    name: frontfuse-network
